# master.yml
# Copyright (C) 2018 shady <shady@MrRobot.local>
#
# Distributed under terms of the MIT license.
#


- hosts: master
  become: true
  tasks:
    - name: initialize the cluster
      shell: kubeadm init --pod-network-cidr=10.244.0.0/16 >> cluster_initialized.txt
      args:
        chdir: $HOME
        creates: cluster_initialized.txt

    - name: create .kube directory
      become: yes
      become_user: shady
      file:
        path: $HOME/.kube
        state: directory
        mode: 0755

    - name: copy admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/shady/.kube/config
        remote_src: yes
        owner: shady

    - name: install Pod network
      become: yes
      become_user: shady
      shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/v0.9.1/Documentation/kube-flannel.yml >> pod_network_setup.txt
      args:
        chdir: $HOME
        creates: pod_network_setup.txt

# vim:ft=ansible
